### ISSUE TITLE
CRLF lines not supported

### ISSUE THREAD

**Issue by lbyonder** [ballercat/walt#153]
# Bug Report
## Overview
Windows style line endings give a syntax error.

## Expected
Documentation should explain what line endings are supported. Does webassembly itself support CRLF?

**Comment by ballercat** [comment]
Thank you for reporting this. Seems like a straightforward bug in the tokenizer. We don't match Window line endings only `\n` so it's invalid syntax. WebAssembly itself isn't opinionated about that type of thing because it's a binary format.

https://github.com/ballercat/walt/blob/7ca5eb833b4d827b326378a78843b1c13bcda687/packages/walt-syntax/src/tokens.js#L76-L102

Should be straightforward to fix with a better regex for `newline`.
