### ISSUE TITLE
Mixture of es-modules & node modules and flow & non-flow files?

### ISSUE THREAD

**Issue by ForsakenHarmony** [ballercat/walt#18]
Is this intentional, or are you transitioning from one to the other?

**Comment by ballercat** [comment]
Hi. The mixture(s) are not intentional; it's just tech debt. I'll spare you the(boring) history of how it got this way, and it's only due to different directions the project took over time.

* I've been slacking on converting everything to flow; it wasn't part of the project initially. 
* Everything should be es6

I would accept PRs for both, but I would want the eslint-flowtype plugin as part of converting everything for flow so that one is a larger effort.

**Comment by ballercat** [comment]
I'm going to close this in favor of #29
